syn on
set wrap
set ts=4
set gfn=Essential\ PragmataPro\ for\ Powerline:h14
set guioptions=cegmt
set guioptions+=LlRrb
set guioptions-=LlRrb
set gcr=n:blinkon0
set lines=40
set columns=90
set fuoptions=maxvert,maxhorz
set wildignore+=*.o,*.obj,.git,*.6,*.a
" set background=light
set background=dark
set fillchars=vert:⏐
set fullscreen
set numberwidth=7
colorscheme base16-eighties
set background=dark
highlight VertSplit term=reverse guifg=#3f2f3f guibg=#2d2d2d
