" generic options
syn on
set wrap
set ts=4
set title
set shortmess=atI
set visualbell
set t_Co=256
colorscheme gardener
set fillchars=vert:⏐
highlight VertSplit term=reverse guifg=#5f5f60 guibg=#202020
" Allow move the cursor left/right to move to the previous/next line when the cursor is on the first/last character in the line.
set ww=<,>,[,]
" enable filetype plugin
filetype plugin on
" enable filetype indent
filetype indent on
" Highlight search terms
set hlsearch
set incsearch " ...dynamically as they are typed.
" If the search term highlighting gets annoying, set a key to switch it off temporarily:
nmap <silent> <leader>n :silent :nohlsearch<CR>
" The following will make tabs and trailing spaces visible when requested:
set listchars=tab:•·,trail:·,eol:$,extends:❯,precedes:❮
set fillchars=vert:⏐
set showbreak=⎖\ 
nmap <silent> <leader>s :set nolist!<CR>
" The current buffer can be put to the background without writing to disk;
" When a background buffer becomes current again, marks and undo-history are remembered.
set hidden
" By default, Vim only remembers the last 20 commands and search patterns entered. It’s nice to boost this up:
set history=1000
" By default, pressing <TAB> in command mode will choose the first possible completion with no indication of how many others there might be. The following configuration lets you see what your other options are:
set wildmenu
" To have the completion behave similarly to a shell, i.e. complete only up to the point of ambiguity (while still showing you what your options are)
set wildmode=list:longest
" These two options, when set together, will make /-style searches case-sensitive only if there is a capital letter in the search expression. *-style searches continue to be consistently case-sensitive.
set ignorecase
set smartcase
" Setting the option below will start the scrolling three lines before the border, keeping more context around where you’re working.
set scrolloff=3
" Swap files and backups are annoying but can save you a lot of trouble. Rather than spread them all around your filesystem, isolate them to a single directory
set backupdir=~/.vim/tmp,/var/tmp,/tmp
set directory=~/.vim/tmp,/var/tmp,/tmp
" It’s often useful to know where you are in a buffer, but full line numbering is distracting. Setting the option below is a good compromise:
set ruler
" set wildignore for CommandT
set wildignore+=*.o,*.obj,.git,*.6,*.out,*.a,_testmain.go
" load bundles from ~/.vim/bundle
call pathogen#runtime_append_all_bundles() 
