# vim: ft=zsh:
[[ -f $DOTFILES/zsh/df/bootstrap ]] && 
    source $DOTFILES/zsh/df/bootstrap

[[ -d $DOTFILES/zsh/df/zshrc.d ]] && 
    for f in $DOTFILES/zsh/df/zshrc.d/*(N); do
        source $f
    done
