#!/bin/bash
if [ -d ~/.bash/bash.d ]; then
    for f in $(ls ~/.bash/bash.d/); do
        . ~/.bash/bash.d/$f
    done
fi

export PATH=~/bin:~/.dotfiles/bin:/usr/local/bin:/usr/local/sbin:${PATH}:/usr/local/share/npm/bin

[[ -s "$HOME/.rvm/scripts/rvm" ]] && source "$HOME/.rvm/scripts/rvm" # Load RVM into a shell session *as a function*
